# Generated by Django 4.2.4 on 2023-10-27 18:07

from django.db import migrations, models
from pages.models import ChecklistItem

def create_checklist_items(apps, schema_editor):
    ChecklistItem = apps.get_model('pages', 'ChecklistItem')
    # Crea instancias de ChecklistItem aquí
    ChecklistItem.objects.create(elementos="Plasticos")
    ChecklistItem.objects.create(elementos="Latas")
    ChecklistItem.objects.create(elementos="Carton")
    ChecklistItem.objects.create(elementos="Papel")
#que mas se puede reciclar? o se dejan esas 4

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementos', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_checklist_items) 
    ]
