# Generated by Django 4.2.5 on 2023-11-15 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='age',
            new_name='puntos',
        ),
    ]
