# Generated by Django 4.2.5 on 2023-11-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_age_userprofile_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='read_news',
            field=models.ManyToManyField(to='pages.news'),
        ),
    ]
