# Generated by Django 4.2.5 on 2023-11-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_userprofile_read_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='read_news',
            field=models.ManyToManyField(blank=True, to='pages.news'),
        ),
    ]
