# Generated by Django 4.2.5 on 2023-11-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_userprofile_read_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='read_news',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='read_news',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
