# Generated by Django 4.2.5 on 2023-11-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_userprofile_read_news_userprofile_read_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='read_news',
            field=models.TextField(blank=True, null=True),
        ),
    ]
