# Generated by Django 4.2.5 on 2023-11-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_userprofile_read_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='read_news',
            new_name='read_news_titles',
        ),
    ]
