# Generated by Django 4.2.5 on 2023-11-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_fecha_checklistitem_item_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='item_name',
            new_name='elementos',
        ),
        migrations.RenameField(
            model_name='checklistitem',
            old_name='item_date',
            new_name='fecha',
        ),
    ]
